#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define TILE_SIZE 64
#define FOV_ANGLE (60 * (PI / 180))
#define NUM_RAYS SCREEN_WIDTH
#define DIST_PROJ_PLANE ((SCREEN_WIDTH / 2) / tan(FOV_ANGLE / 2))
#define MINIMAP_SCALE_FACTOR 0.2

#define FRAME_TIME_LENGTH (1000 / 60)
#define PI 3.14159265

#endif /* CONFIG_H */

